// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4RYbMuUvhTInpzyqkuUilLWO6qi0eM8',
    appId: '1:1080735933564:web:a7906c152fb83074cc95f9',
    messagingSenderId: '1080735933564',
    projectId: 'duplotwin',
    authDomain: 'duplotwin.firebaseapp.com',
    storageBucket: 'duplotwin.appspot.com',
    measurementId: 'G-YDPPVDRBCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_pEyReP4YaqtXLrD6ygxk_zUB4POMVJc',
    appId: '1:1080735933564:android:a92d2ee5b1055d23cc95f9',
    messagingSenderId: '1080735933564',
    projectId: 'duplotwin',
    storageBucket: 'duplotwin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnZ0S89tamRN7McjEYh42Axa-MFG39MY',
    appId: '1:1080735933564:ios:1109fdc02666d9edcc95f9',
    messagingSenderId: '1080735933564',
    projectId: 'duplotwin',
    storageBucket: 'duplotwin.appspot.com',
    iosClientId: '1080735933564-3an54fhaa72se3l2mnh9hsbl4k5oov2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.duplotwin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPnZ0S89tamRN7McjEYh42Axa-MFG39MY',
    appId: '1:1080735933564:ios:1109fdc02666d9edcc95f9',
    messagingSenderId: '1080735933564',
    projectId: 'duplotwin',
    storageBucket: 'duplotwin.appspot.com',
    iosClientId: '1080735933564-3an54fhaa72se3l2mnh9hsbl4k5oov2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.duplotwin',
  );
}
